-- Generated by protobuf; do not edit
local module = {}
local protobuf = require 'protobuf'

module.SHOP_RAW = protobuf.Descriptor()
module.SHOP_RAW_COLOUR_FIELD = protobuf.FieldDescriptor()
module.SHOP_RAW_DISCOUNT_FIELD = protobuf.FieldDescriptor()
module.SHOP_RAW_RATINGS_COUNT_FIELD = protobuf.FieldDescriptor()
module.SHOP_RAW_PRICE_FIELD = protobuf.FieldDescriptor()
module.SHOP_RAW_RATINGS_FIELD = protobuf.FieldDescriptor()
module.SHOP_PROCESSED = protobuf.Descriptor()
module.SHOP_PROCESSED_COLOUR_FIELD = protobuf.FieldDescriptor()
module.SHOP_PROCESSED_DISCOUNT_FIELD = protobuf.FieldDescriptor()
module.SHOP_PROCESSED_RATINGS_COUNT_FIELD = protobuf.FieldDescriptor()
module.SHOP_PROCESSED_PRICE_FIELD = protobuf.FieldDescriptor()
module.SHOP_PROCESSED_RATINGS_FIELD = protobuf.FieldDescriptor()
module.SHOP_PROCESSED_SCORE_FIELD = protobuf.FieldDescriptor()

module.SHOP_RAW_COLOUR_FIELD.name = 'Colour'
module.SHOP_RAW_COLOUR_FIELD.full_name = '.Shop_Raw.Colour'
module.SHOP_RAW_COLOUR_FIELD.number = 1
module.SHOP_RAW_COLOUR_FIELD.index = 0
module.SHOP_RAW_COLOUR_FIELD.label = 2
module.SHOP_RAW_COLOUR_FIELD.has_default_value = false
module.SHOP_RAW_COLOUR_FIELD.default_value = ''
module.SHOP_RAW_COLOUR_FIELD.type = 9
module.SHOP_RAW_COLOUR_FIELD.cpp_type = 9

module.SHOP_RAW_DISCOUNT_FIELD.name = 'Discount'
module.SHOP_RAW_DISCOUNT_FIELD.full_name = '.Shop_Raw.Discount'
module.SHOP_RAW_DISCOUNT_FIELD.number = 2
module.SHOP_RAW_DISCOUNT_FIELD.index = 1
module.SHOP_RAW_DISCOUNT_FIELD.label = 2
module.SHOP_RAW_DISCOUNT_FIELD.has_default_value = false
module.SHOP_RAW_DISCOUNT_FIELD.default_value = 0
module.SHOP_RAW_DISCOUNT_FIELD.type = 5
module.SHOP_RAW_DISCOUNT_FIELD.cpp_type = 1

module.SHOP_RAW_RATINGS_COUNT_FIELD.name = 'Ratings_count'
module.SHOP_RAW_RATINGS_COUNT_FIELD.full_name = '.Shop_Raw.Ratings_count'
module.SHOP_RAW_RATINGS_COUNT_FIELD.number = 3
module.SHOP_RAW_RATINGS_COUNT_FIELD.index = 2
module.SHOP_RAW_RATINGS_COUNT_FIELD.label = 2
module.SHOP_RAW_RATINGS_COUNT_FIELD.has_default_value = false
module.SHOP_RAW_RATINGS_COUNT_FIELD.default_value = 0
module.SHOP_RAW_RATINGS_COUNT_FIELD.type = 5
module.SHOP_RAW_RATINGS_COUNT_FIELD.cpp_type = 1

module.SHOP_RAW_PRICE_FIELD.name = 'Price'
module.SHOP_RAW_PRICE_FIELD.full_name = '.Shop_Raw.Price'
module.SHOP_RAW_PRICE_FIELD.number = 4
module.SHOP_RAW_PRICE_FIELD.index = 3
module.SHOP_RAW_PRICE_FIELD.label = 2
module.SHOP_RAW_PRICE_FIELD.has_default_value = false
module.SHOP_RAW_PRICE_FIELD.default_value = 0
module.SHOP_RAW_PRICE_FIELD.type = 5
module.SHOP_RAW_PRICE_FIELD.cpp_type = 1

module.SHOP_RAW_RATINGS_FIELD.name = 'Ratings'
module.SHOP_RAW_RATINGS_FIELD.full_name = '.Shop_Raw.Ratings'
module.SHOP_RAW_RATINGS_FIELD.number = 5
module.SHOP_RAW_RATINGS_FIELD.index = 4
module.SHOP_RAW_RATINGS_FIELD.label = 2
module.SHOP_RAW_RATINGS_FIELD.has_default_value = false
module.SHOP_RAW_RATINGS_FIELD.default_value = 0.0
module.SHOP_RAW_RATINGS_FIELD.type = 2
module.SHOP_RAW_RATINGS_FIELD.cpp_type = 6

module.SHOP_RAW.name = 'Shop_Raw'
module.SHOP_RAW.full_name = '.Shop_Raw'
module.SHOP_RAW.nested_types = {}
module.SHOP_RAW.enum_types = {}
module.SHOP_RAW.fields = {module.SHOP_RAW_COLOUR_FIELD, module.SHOP_RAW_DISCOUNT_FIELD, module.SHOP_RAW_RATINGS_COUNT_FIELD, module.SHOP_RAW_PRICE_FIELD, module.SHOP_RAW_RATINGS_FIELD}
module.SHOP_RAW.is_extendable = false
module.SHOP_RAW.extensions = {}
module.SHOP_PROCESSED_COLOUR_FIELD.name = 'Colour'
module.SHOP_PROCESSED_COLOUR_FIELD.full_name = '.Shop_Processed.Colour'
module.SHOP_PROCESSED_COLOUR_FIELD.number = 1
module.SHOP_PROCESSED_COLOUR_FIELD.index = 0
module.SHOP_PROCESSED_COLOUR_FIELD.label = 2
module.SHOP_PROCESSED_COLOUR_FIELD.has_default_value = false
module.SHOP_PROCESSED_COLOUR_FIELD.default_value = ''
module.SHOP_PROCESSED_COLOUR_FIELD.type = 9
module.SHOP_PROCESSED_COLOUR_FIELD.cpp_type = 9

module.SHOP_PROCESSED_DISCOUNT_FIELD.name = 'Discount'
module.SHOP_PROCESSED_DISCOUNT_FIELD.full_name = '.Shop_Processed.Discount'
module.SHOP_PROCESSED_DISCOUNT_FIELD.number = 2
module.SHOP_PROCESSED_DISCOUNT_FIELD.index = 1
module.SHOP_PROCESSED_DISCOUNT_FIELD.label = 2
module.SHOP_PROCESSED_DISCOUNT_FIELD.has_default_value = false
module.SHOP_PROCESSED_DISCOUNT_FIELD.default_value = 0
module.SHOP_PROCESSED_DISCOUNT_FIELD.type = 5
module.SHOP_PROCESSED_DISCOUNT_FIELD.cpp_type = 1

module.SHOP_PROCESSED_RATINGS_COUNT_FIELD.name = 'Ratings_count'
module.SHOP_PROCESSED_RATINGS_COUNT_FIELD.full_name = '.Shop_Processed.Ratings_count'
module.SHOP_PROCESSED_RATINGS_COUNT_FIELD.number = 3
module.SHOP_PROCESSED_RATINGS_COUNT_FIELD.index = 2
module.SHOP_PROCESSED_RATINGS_COUNT_FIELD.label = 2
module.SHOP_PROCESSED_RATINGS_COUNT_FIELD.has_default_value = false
module.SHOP_PROCESSED_RATINGS_COUNT_FIELD.default_value = 0
module.SHOP_PROCESSED_RATINGS_COUNT_FIELD.type = 5
module.SHOP_PROCESSED_RATINGS_COUNT_FIELD.cpp_type = 1

module.SHOP_PROCESSED_PRICE_FIELD.name = 'Price'
module.SHOP_PROCESSED_PRICE_FIELD.full_name = '.Shop_Processed.Price'
module.SHOP_PROCESSED_PRICE_FIELD.number = 4
module.SHOP_PROCESSED_PRICE_FIELD.index = 3
module.SHOP_PROCESSED_PRICE_FIELD.label = 2
module.SHOP_PROCESSED_PRICE_FIELD.has_default_value = false
module.SHOP_PROCESSED_PRICE_FIELD.default_value = 0
module.SHOP_PROCESSED_PRICE_FIELD.type = 5
module.SHOP_PROCESSED_PRICE_FIELD.cpp_type = 1

module.SHOP_PROCESSED_RATINGS_FIELD.name = 'Ratings'
module.SHOP_PROCESSED_RATINGS_FIELD.full_name = '.Shop_Processed.Ratings'
module.SHOP_PROCESSED_RATINGS_FIELD.number = 5
module.SHOP_PROCESSED_RATINGS_FIELD.index = 4
module.SHOP_PROCESSED_RATINGS_FIELD.label = 2
module.SHOP_PROCESSED_RATINGS_FIELD.has_default_value = false
module.SHOP_PROCESSED_RATINGS_FIELD.default_value = 0.0
module.SHOP_PROCESSED_RATINGS_FIELD.type = 2
module.SHOP_PROCESSED_RATINGS_FIELD.cpp_type = 6

module.SHOP_PROCESSED_SCORE_FIELD.name = 'Score'
module.SHOP_PROCESSED_SCORE_FIELD.full_name = '.Shop_Processed.Score'
module.SHOP_PROCESSED_SCORE_FIELD.number = 6
module.SHOP_PROCESSED_SCORE_FIELD.index = 5
module.SHOP_PROCESSED_SCORE_FIELD.label = 2
module.SHOP_PROCESSED_SCORE_FIELD.has_default_value = false
module.SHOP_PROCESSED_SCORE_FIELD.default_value = 0.0
module.SHOP_PROCESSED_SCORE_FIELD.type = 2
module.SHOP_PROCESSED_SCORE_FIELD.cpp_type = 6

module.SHOP_PROCESSED.name = 'Shop_Processed'
module.SHOP_PROCESSED.full_name = '.Shop_Processed'
module.SHOP_PROCESSED.nested_types = {}
module.SHOP_PROCESSED.enum_types = {}
module.SHOP_PROCESSED.fields = {module.SHOP_PROCESSED_COLOUR_FIELD, module.SHOP_PROCESSED_DISCOUNT_FIELD, module.SHOP_PROCESSED_RATINGS_COUNT_FIELD, module.SHOP_PROCESSED_PRICE_FIELD, module.SHOP_PROCESSED_RATINGS_FIELD, module.SHOP_PROCESSED_SCORE_FIELD}
module.SHOP_PROCESSED.is_extendable = false
module.SHOP_PROCESSED.extensions = {}

module.Shop_Processed = protobuf.Message(module.SHOP_PROCESSED)
module.Shop_Raw = protobuf.Message(module.SHOP_RAW)


module.MESSAGE_TYPES = {'Shop_Raw','Shop_Processed'}
module.ENUM_TYPES = {}

return module
